name: Build React on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main # リポジトリをチェックアウト

      - name: Install Dependencies
        run: mkdir .aws && touch credentials && cd frontend && yarn install

      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY" > .aws/credentials && cd frontend && aws s3 cp --recursive --include "*" --region ap-northeast-1 build s3://static-site-for-taka-test