name: Build React on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main #リポジトリをチェックアウト

      - name: Install Dependencies
        run: cd frontend && yarn install

      - name: Build
        run: cd frontend && pwd && yarn build # React ビルド

      #- name: Deploy  # S3にデプロイ
        #uses: aws-actions/configure-aws-credentials@v1
        #env:
          #AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #with:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: ap-northeast-1

      - name: Copy Files to s3
        #run: |
          #cd frontend && aws s3 sync ./build s3://static-site-for-taka-test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd frontend && aws s3 cp --recursive --region ap-northeast-1 build s3://bucket-for-deploying-react-project