name: Upload to S3
#-------------------------#
# トリガー
#-------------------------#
on:
  #-- mainブランチにpushされたら起動する --#
  push:
      branches:
        - main

#-------------------------#
# 実際の処理
#-------------------------#
jobs:
  build:
    #-- 仮想マシンのOSを指定（ここではUbuntuの最新版） --#
    runs-on: ubuntu-latest
    steps:
      #-- Gitリポジトリの内容を取得 --#
      - name: Checkout
        uses: actions/checkout@v2

      - name: EnvVariable
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo ${{ env.AWS_ACCESS_KEY_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $env.AWS_ACCESS_KEY_ID
          aws-secret-access-key: $env.AWS_SECRET_ACCESS_KEY
          aws-region: ap-northeast-1
          role-session-name: deploy-role-session

      - name: Deploy to S3
        #-- 仮想マシン上でコマンドを実行 --#
        run:
          #aws s3 cp -r --recursive --region ap-northeast-1 frontend/build s3://static-site-for-taka-test
          cd frontend && aws s3 cp --recursive build/ s3://static-site-for-taka-test