name: Build React on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main #リポジトリをチェックアウト

      - name: Install Dependencies
        run: cd frontend && yarn install

      - name: Build
        run: cd frontend && pwd && yarn build # React ビルド
    
      - name: Deploy  # S3にデプロイ
        env:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        run: |
          cd frontend && aws s3 cp --recursive --include "*" --region ap-northeast-1 build s3://static-site-for-taka-test